/home/sherstancraig/work/clean_sr/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:146: UserWarning:
NVIDIA GeForce RTX 3080 Ti Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Ti Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
evaluate_agent (LunarLanderContinuous-v2)
Traceback (most recent call last):
  File "/home/sherstancraig/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/sherstancraig/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sherstancraig/work/clean_sr/baseline.py", line 344, in <module>
    baseline(Args("baseline"))
  File "/home/sherstancraig/work/clean_sr/baseline.py", line 184, in baseline
    eval_agent(agent=agent,
  File "/home/sherstancraig/work/clean_sr/common.py", line 85, in eval_agent
    episode_returns, episode_lengths = evaluate_agent(agent, #state_dict=agent.state_dict(),
  File "/home/sherstancraig/work/clean_sr/common.py", line 62, in evaluate_agent
    actions, _, _, _ = agent.get_action_and_value(torch.Tensor(obs).to(device))
  File "/home/sherstancraig/work/clean_sr/baseline.py", line 41, in get_action_and_value
    action_mean = self.actor_mean(x)
  File "/home/sherstancraig/work/clean_sr/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sherstancraig/work/clean_sr/.venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/sherstancraig/work/clean_sr/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sherstancraig/work/clean_sr/.venv/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 354, in forward
    return torch.tanh(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
